# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from tokenize import Double
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(336, 556)
        self.centralwidget = QtWidgets.QWidget(Calculator)
        self.centralwidget.setObjectName("centralwidget")
        self.InputOfCal = QtWidgets.QLabel(self.centralwidget)
        self.InputOfCal.setGeometry(QtCore.QRect(10, 20, 311, 91))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.InputOfCal.setFont(font)
        self.InputOfCal.setAutoFillBackground(False)
        self.InputOfCal.setFrameShape(QtWidgets.QFrame.Box)
        self.InputOfCal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InputOfCal.setScaledContents(False)
        self.InputOfCal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.InputOfCal.setIndent(-2)
        self.InputOfCal.setObjectName("InputOfCal")
        self.percentButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.percentageIt())
        self.percentButton.setGeometry(QtCore.QRect(10, 120, 75, 75))
        self.percentButton.setBaseSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.percentButton.setFont(font)
        self.percentButton.setObjectName("percentButton")
        self.CButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.pressedIt("C"))
        self.CButton.setGeometry(QtCore.QRect(90, 120, 75, 75))
        self.CButton.setBaseSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.CButton.setFont(font)
        self.CButton.setObjectName("CButton")
        self.lessThanButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.removeIt())
        self.lessThanButton.setGeometry(QtCore.QRect(170, 120, 75, 75))
        self.lessThanButton.setBaseSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lessThanButton.setFont(font)
        self.lessThanButton.setObjectName("lessThanButton")
        self.divButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.pressedIt("/"))
        self.divButton.setGeometry(QtCore.QRect(250, 120, 75, 75))
        self.divButton.setBaseSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.divButton.setFont(font)
        self.divButton.setObjectName("divButton")
        self.eightButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.pressedIt("8"))
        self.eightButton.setGeometry(QtCore.QRect(90, 200, 75, 75))
        self.eightButton.setBaseSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.eightButton.setFont(font)
        self.eightButton.setObjectName("eightButton")
        self.nineButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.pressedIt("9"))
        self.nineButton.setGeometry(QtCore.QRect(170, 200, 75, 75))
        self.nineButton.setBaseSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nineButton.setFont(font)
        self.nineButton.setObjectName("nineButton")
        self.multiplyButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.pressedIt("*"))
        self.multiplyButton.setGeometry(QtCore.QRect(250, 200, 75, 75))
        self.multiplyButton.setBaseSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.multiplyButton.setFont(font)
        self.multiplyButton.setObjectName("multiplyButton")
        self.sevenButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.pressedIt("7"))
        self.sevenButton.setGeometry(QtCore.QRect(10, 200, 75, 75))
        self.sevenButton.setBaseSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sevenButton.setFont(font)
        self.sevenButton.setObjectName("sevenButton")
        self.fiveButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.pressedIt("5"))
        self.fiveButton.setGeometry(QtCore.QRect(90, 280, 75, 75))
        self.fiveButton.setBaseSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.fiveButton.setFont(font)
        self.fiveButton.setObjectName("fiveButton")
        self.sixButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.pressedIt("6"))
        self.sixButton.setGeometry(QtCore.QRect(170, 280, 75, 75))
        self.sixButton.setBaseSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sixButton.setFont(font)
        self.sixButton.setObjectName("sixButton")
        self.minusButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.pressedIt("-"))
        self.minusButton.setGeometry(QtCore.QRect(250, 280, 75, 75))
        self.minusButton.setBaseSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.minusButton.setFont(font)
        self.minusButton.setObjectName("minusButton")
        self.fourButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.pressedIt("4"))
        self.fourButton.setGeometry(QtCore.QRect(10, 280, 75, 75))
        self.fourButton.setBaseSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.fourButton.setFont(font)
        self.fourButton.setObjectName("fourButton")
        self.oneButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.pressedIt("1"))
        self.oneButton.setGeometry(QtCore.QRect(10, 360, 75, 75))
        self.oneButton.setBaseSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oneButton.setFont(font)
        self.oneButton.setObjectName("oneButton")
        self.plusButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.pressedIt("+"))
        self.plusButton.setGeometry(QtCore.QRect(250, 360, 75, 75))
        self.plusButton.setBaseSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.plusButton.setFont(font)
        self.plusButton.setObjectName("plusButton")
        self.twoButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.pressedIt("2"))
        self.twoButton.setGeometry(QtCore.QRect(90, 360, 75, 75))
        self.twoButton.setBaseSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.twoButton.setFont(font)
        self.twoButton.setObjectName("twoButton")
        self.threeButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.pressedIt("3"))
        self.threeButton.setGeometry(QtCore.QRect(170, 360, 75, 75))
        self.threeButton.setBaseSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.threeButton.setFont(font)
        self.threeButton.setObjectName("threeButton")
        self.plusMinusButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.plusMinusIt())
        self.plusMinusButton.setGeometry(QtCore.QRect(10, 440, 75, 75))
        self.plusMinusButton.setBaseSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.plusMinusButton.setFont(font)
        self.plusMinusButton.setObjectName("plusMinusButton")
        self.equalToButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.answerIt())
        self.equalToButton.setGeometry(QtCore.QRect(250, 440, 75, 75))
        self.equalToButton.setBaseSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.equalToButton.setFont(font)
        self.equalToButton.setObjectName("equalToButton")
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.pressedIt("0"))
        self.zeroButton.setGeometry(QtCore.QRect(90, 440, 75, 75))
        self.zeroButton.setBaseSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.zeroButton.setFont(font)
        self.zeroButton.setObjectName("zeroButton")
        self.decimalButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.dotIt())
        self.decimalButton.setGeometry(QtCore.QRect(170, 440, 75, 75))
        self.decimalButton.setBaseSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.decimalButton.setFont(font)
        self.decimalButton.setObjectName("decimalButton")
        Calculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Calculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 336, 26))
        self.menubar.setObjectName("menubar")
        Calculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Calculator)
        self.statusbar.setObjectName("statusbar")
        Calculator.setStatusBar(self.statusbar)

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    # Function space 

    # percentage functionality
    def percentageIt(self):
        screen = self.InputOfCal.text()
        try:
            val = Double(screen)
            percent = val/100
            self.InputOfCal.setText(f'{percent}%')
        except:
            self.InputOfCal.setText("ERROR")

    # equalToButton functionality
    def answerIt(self):
        screen = self.InputOfCal.text()
        try:
            answer = eval(screen)
            self.InputOfCal.setText(f'{answer}')
        except:
            self.InputOfCal.setText(f'ERROR') 


    # Plus minus functionality
    def plusMinusIt(self):
        screen = self.InputOfCal.text()
        if "-" in screen:
            self.InputOfCal.setText(screen.replace("-","+"))
        else:
            self.InputOfCal.setText(screen.replace("+","-"))


    # Adding a decimal point to the number
    def dotIt(self):
        screen = self.InputOfCal.text()
        if "." in screen:
            pass
        else:
            self.InputOfCal.setText(f'{screen}.')

    # Generic press button
    def pressedIt(self,pressed):
        if pressed == 'C':
            self.InputOfCal.setText("0")
        else:
            if self.InputOfCal.text() == "0":
                self.InputOfCal.setText("")
            self.InputOfCal.setText(f' {self.InputOfCal.text()}{pressed}')

    def removeIt(self):
        screen = self.InputOfCal.text()
        # removing the last element
        screen = screen[:-1]
        self.InputOfCal.setText(f'{screen}')


    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "MainWindow"))
        self.InputOfCal.setText(_translate("Calculator", "0"))
        self.percentButton.setText(_translate("Calculator", "%"))
        self.CButton.setText(_translate("Calculator", "C"))
        self.lessThanButton.setText(_translate("Calculator", "<<"))
        self.divButton.setText(_translate("Calculator", "/"))
        self.eightButton.setText(_translate("Calculator", "8"))
        self.nineButton.setText(_translate("Calculator", "9"))
        self.multiplyButton.setText(_translate("Calculator", "x"))
        self.sevenButton.setText(_translate("Calculator", "7"))
        self.fiveButton.setText(_translate("Calculator", "5"))
        self.sixButton.setText(_translate("Calculator", "6"))
        self.minusButton.setText(_translate("Calculator", "-"))
        self.fourButton.setText(_translate("Calculator", "4"))
        self.oneButton.setText(_translate("Calculator", "1"))
        self.plusButton.setText(_translate("Calculator", "+"))
        self.twoButton.setText(_translate("Calculator", "2"))
        self.threeButton.setText(_translate("Calculator", "3"))
        self.plusMinusButton.setText(_translate("Calculator", "+/-"))
        self.equalToButton.setText(_translate("Calculator", "="))
        self.zeroButton.setText(_translate("Calculator", "0"))
        self.decimalButton.setText(_translate("Calculator", "."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculator = QtWidgets.QMainWindow()
    ui = Ui_Calculator()
    ui.setupUi(Calculator)
    Calculator.show()
    sys.exit(app.exec_())
