# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkBox2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(351, 279)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 170, 161, 41))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.RedCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.RedCheckBox.setGeometry(QtCore.QRect(170, 50, 81, 20))
        self.RedCheckBox.setObjectName("RedCheckBox")
        self.BlueCheckBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.BlueCheckBox_2.setGeometry(QtCore.QRect(170, 110, 81, 20))
        self.BlueCheckBox_2.setObjectName("BlueCheckBox_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Pick A Color"))
        self.RedCheckBox.setText(_translate("MainWindow", "Red"))
        self.BlueCheckBox_2.setText(_translate("MainWindow", "Blue"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
