# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connect1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mian(object):
    def setupUi(self, Mian):
        Mian.setObjectName("Mian")
        Mian.resize(372, 374)
        self.submitButton = QtWidgets.QPushButton(Mian)
        self.submitButton.setGeometry(QtCore.QRect(10, 210, 351, 61))
        self.submitButton.setObjectName("submitButton")
        self.openButton = QtWidgets.QPushButton(Mian)
        self.openButton.setGeometry(QtCore.QRect(10, 290, 351, 61))
        self.openButton.setObjectName("openButton")
        self.lineEdit = QtWidgets.QLineEdit(Mian)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 351, 191))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Mian)
        QtCore.QMetaObject.connectSlotsByName(Mian)

    def retranslateUi(self, Mian):
        _translate = QtCore.QCoreApplication.translate
        Mian.setWindowTitle(_translate("Mian", "Dialog"))
        self.submitButton.setText(_translate("Mian", "Submit"))
        self.openButton.setText(_translate("Mian", "Open Window"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mian = QtWidgets.QDialog()
    ui = Ui_Mian()
    ui.setupUi(Mian)
    Mian.show()
    sys.exit(app.exec_())
