# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'First.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QtUI(object):
    def setupUi(self, QtUI):
        QtUI.setObjectName("QtUI")
        QtUI.resize(670, 531)
        self.myButton = QtWidgets.QPushButton(QtUI,clicked= lambda: self.pressed())
        self.myButton.setGeometry(QtCore.QRect(140, 280, 431, 161))
        self.myButton.setObjectName("myButton")
        self.myLabel = QtWidgets.QLabel(QtUI)
        self.myLabel.setGeometry(QtCore.QRect(250, 120, 191, 131))
        self.myLabel.setSizeIncrement(QtCore.QSize(34, 34))
        self.myLabel.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.myLabel.setFont(font)
        self.myLabel.setAutoFillBackground(False)
        self.myLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.myLabel.setObjectName("myLabel")

        self.retranslateUi(QtUI)
        QtCore.QMetaObject.connectSlotsByName(QtUI)

    # Function Space
    def pressed(self):
        self.myLabel.setText("Boom!")

    def retranslateUi(self, QtUI):
        _translate = QtCore.QCoreApplication.translate
        QtUI.setWindowTitle(_translate("QtUI", "Form"))
        self.myButton.setText(_translate("QtUI", "Press me"))
        self.myLabel.setText(_translate("QtUI", " First UI"))

    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QtUI = QtWidgets.QWidget()
    ui = Ui_QtUI()
    ui.setupUi(QtUI)
    QtUI.show()
    sys.exit(app.exec_())
